export default {
    Skeleton: {
        Health: 60,
        Defense: 0,
        Speed: 4,
        Damage: 0,
        Cooldown: 0,
        Tick: 0,
        Range: 2,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Sword Skeleton': {
        Health: 90,
        Defense: 0,
        Speed: 3.5,
        Damage: 20,
        Cooldown: 0.8,
        Tick: 0,
        Range: 7.5,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Giant Skeleton': {
        Health: 600,
        Defense: 0,
        Speed: 2.4,
        Damage: 0,
        Cooldown: 0,
        Tick: 0,
        Range: 2,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Skeleton Knight': {
        Health: 250,
        Defense: 0,
        Speed: 3.5,
        Damage: 90,
        Cooldown: 0.65,
        Tick: 0,
        Range: 7.5,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Hallow Guard': {
        Health: 1500,
        Defense: 20,
        Speed: 2.4,
        Damage: 0,
        Cooldown: 0,
        Tick: 0,
        Range: 2,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Executioner Skeleton': {
        Health: 3500,
        Defense: 0,
        Speed: 1.2,
        Damage: 50,
        Cooldown: 3,
        Tick: 0.1,
        Range: 30,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
        Attributes: {},
    },
    'Skeleton (PVP)': {
        Health: 60,
        Defense: 0,
        Speed: 4,
        Damage: 0,
        Cooldown: 0,
        Tick: 0,
        Range: 2,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Sword Skeleton (PVP)': {
        Health: 90,
        Defense: 0,
        Speed: 3.5,
        Damage: 20,
        Cooldown: 0.8,
        Tick: 0,
        Range: 6,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Giant Skeleton (PVP)': {
        Health: 600,
        Defense: 0,
        Speed: 2.4,
        Damage: 0,
        Cooldown: 0,
        Tick: 0,
        Range: 2,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Skeleton Knight (PVP)': {
        Health: 250,
        Defense: 0,
        Speed: 3.5,
        Damage: 90,
        Cooldown: 0.65,
        Tick: 0,
        Range: 6,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Hallow Guard (PVP)': {
        Health: 1500,
        Defense: 20,
        Speed: 2.4,
        Damage: 0,
        Cooldown: 0,
        Tick: 0,
        Range: 2,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {},
    },
    'Executioner Skeleton (PVP)': {
        Health: 3500,
        Defense: 0,
        Speed: 1.2,
        Damage: 50,
        Cooldown: 3,
        Tick: 0.1,
        Range: 30,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
        Attributes: {},
    },
    Goon1: {
        Range: 20,
        Health: 15,
        Cooldown: 1,
        Damage: 3,
        SpawnTime: 50,
        Lifespan: 150,
        Limit: 10,
        Speed: 4,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
    },
    Goon2: {
        Range: 17,
        Health: 100,
        Cooldown: 0.2,
        Damage: 4,
        SpawnTime: 50,
        Lifespan: 200,
        Limit: 4,
        Speed: 4,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Goon3: {
        Range: 18,
        Health: 175,
        Cooldown: 0.12,
        Damage: 10,
        SpawnTime: 50,
        Lifespan: 200,
        Limit: 4,
        Speed: 4,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    ['Goon1 (PVP)']: {
        Range: 18,
        Health: 25,
        Cooldown: 0.8,
        Damage: 2,
        SpawnTime: 50,
        Lifespan: 150,
        Limit: 10,
        Speed: 4,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
    },
    ['Goon2 (PVP)']: {
        Range: 20,
        Health: 125,
        Cooldown: 0.25,
        Damage: 5,
        SpawnTime: 50,
        Lifespan: 200,
        Limit: 4,
        Speed: 4,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    ['Goon3 (PVP)']: {
        Range: 20,
        Health: 225,
        Cooldown: 0.12,
        Damage: 8,
        SpawnTime: 50,
        Lifespan: 200,
        Limit: 4,
        Speed: 4,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    GoldenGoon1: {
        Range: 20,
        Health: 25,
        Cooldown: 0.6,
        Damage: 3,
        SpawnTime: 50,
        Lifespan: 150,
        Limit: 10,
        Speed: 4,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
    },
    GoldenGoon2: {
        Range: 17.5,
        Health: 125,
        Cooldown: 0.18,
        Damage: 5,
        SpawnTime: 50,
        Lifespan: 200,
        Limit: 4,
        Speed: 4,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    GoldenGoon3: {
        Range: 20,
        Health: 225,
        Cooldown: 0.1,
        Damage: 12,
        SpawnTime: 50,
        Lifespan: 200,
        Limit: 4,
        Speed: 4,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    // Mercenary base
    Rifleman1: {
        Unlocks: 0,
        Health: 40,
        Speed: 3.5,
        MaxSpeed: 3.5,
        Defense: 0,
        Damage: 6,
        BurstAmount: 6,
        SpawnTime: 40,
        Heal: 0,
        MaxHits: 1,
        Cooldown: 0.15,
        BurstCooldown: 1,
        AimTime: 0.35,
        Lifespan: 240,
        Limit: 10,
        Range: 20,
        ChargeTime: 0, 
        ExplosionRange: 0,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    Rifleman2: {
        Unlocks: 3,
        Health: 75,
        Speed: 3.5,
        MaxSpeed: 3.5,
        Defense: 0,
        Damage: 11,
        BurstAmount: 8,
        SpawnTime: 40,
        MaxHits: 1,
        Cooldown: 0.15,
        BurstCooldown: 1,
        AimTime: 0.35,
        Lifespan: 240,
        Limit: 10,
        Range: 24,
        ChargeTime: 0, 
        ExplosionRange: 0,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
    },
    Rifleman3: {
        Unlocks: 6,
        Health: 275,
        Speed: 3.5,
        MaxSpeed: 3.5,
        Defense: 0,
        Damage: 25,
        BurstAmount: 8,
        SpawnTime: 40,
        MaxHits: 1,
        Cooldown: 0.15,
        BurstCooldown: 1,
        AimTime: 0.35,
        Lifespan: 240,
        Limit: 10,
        Range: 30,
        ChargeTime: 0, 
        ExplosionRange: 0,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
    },
    Grenadier1: {
        Unlocks: 1,
        Health: 50,
        Speed: 2.5,
        Defense: 0,
        Damage: 25,
        SpawnTime: 35,
        Cooldown: 1.5,
        Lifespan: 240,
        Limit: 7,
        Range: 19,
        ChargeTime: 0, 
        ExplosionRange: 4.5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    Grenadier2: {
        Unlocks: 3,
        Health: 135,
        Speed: 2.5,
        Defense: 0,
        Damage: 40,
        SpawnTime: 35,
        Cooldown: 1.25,
        Lifespan: 240,
        Limit: 7,
        Range: 20,
        ChargeTime: 0, 
        ExplosionRange: 5.5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    Grenadier3: {
        Unlocks: 6,
        Health: 325,
        Speed: 2.5,
        Defense: 10,
        Damage: 75,
        SpawnTime: 35,
        Cooldown: 1.1,
        Lifespan: 240,
        Limit: 7,
        Range: 22.5,
        ChargeTime: 0, 
        ExplosionRange: 7,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    RiotGuard1: {
        Unlocks: 4,
        Health: 1000,
        Speed: 2.5,
        MaxSpeed: 7,
        Defense: 10,
        Damage: 50,
        SpawnTime: 50,
        MaxHits: 10,
        Cooldown: 1.5,
        Lifespan: 240,
        Limit: 4,
        Range: 4,
        ChargeTime: 4, 
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    RiotGuard2: {
        Unlocks: 6,
        Health: 2600,
        Speed: 2.5,
        MaxSpeed: 7,
        Defense: 15,
        Damage: 50,
        SpawnTime: 50,
        MaxHits: 10,
        Cooldown: 1,
        Lifespan: 240,
        Limit: 4,
        Range: 4,
        ChargeTime: 3, 
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    FieldMedic1: {
        Unlocks: 5,
        Health: 300,
        Speed: 2.5,
        Defense: 0,
        SpawnTime: 35,
        Heal: 15,
        MaxHits: 8,
        Cooldown: 0.2,
        Lifespan: 240,
        Limit: 3,
        Range: 30,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    FieldMedic2: {
        Unlocks: 6,
        Health: 800,
        Speed: 2.5,
        Defense: 0,
        SpawnTime: 30,
        Heal: 20,
        MaxHits: 10,
        Cooldown: 0.2,
        Lifespan: 240,
        Limit: 3,
        Range: 30,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    ['Rifleman1 (PVP)']: {
        Unlocks: 0,
        Health: 40,
        Speed: 3.5,
        MaxSpeed: 3.5,
        Defense: 0,
        Damage: 6,
        BurstAmount: 6,
        SpawnTime: 45,
        Heal: 0,
        MaxHits: 1,
        Cooldown: 0.15,
        BurstCooldown: 1,
        AimTime: 0.35,
        Lifespan: 240,
        Limit: 10,
        Range: 20,
        ChargeTime: 0, 
        ExplosionRange: 0,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    ['Rifleman2 (PVP)']: {
        Unlocks: 3,
        Health: 70,
        Speed: 3.5,
        MaxSpeed: 3.5,
        Defense: 0,
        Damage: 11,
        BurstAmount: 8,
        SpawnTime: 40,
        Heal: 0,
        MaxHits: 1,
        Cooldown: 0.15,
        BurstCooldown: 1,
        AimTime: 0.35,
        Lifespan: 240,
        Limit: 10,
        Range: 24,
        ChargeTime: 0, 
        ExplosionRange: 0,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
    },
    ['Rifleman3 (PVP)']: {
        Unlocks: 6,
        Health: 275,
        Speed: 3.5,
        MaxSpeed: 3.5,
        Defense: 0,
        Damage: 25,
        BurstAmount: 10,
        SpawnTime: 40,
        Heal: 0,
        MaxHits: 1,
        Cooldown: 0.15,
        BurstCooldown: 1,
        AimTime: 0.35,
        Lifespan: 240,
        Limit: 10,
        Range: 28,
        ChargeTime: 0, 
        ExplosionRange: 0,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
    },
    ['Grenadier1 (PVP)']: {
        Unlocks: 1,
        Health: 50,
        Speed: 2.5,
        Defense: 0,
        Damage: 28,
        SpawnTime: 40,
        Heal: 0,
        Cooldown: 1.75,
        Lifespan: 240,
        Limit: 7,
        Range: 18,
        ChargeTime: 0, 
        ExplosionRange: 3,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    ['Grenadier2 (PVP)']: {
        Unlocks: 3,
        Health: 125,
        Speed: 2.5,
        Defense: 0,
        Damage: 50,
        SpawnTime: 40,
        Heal: 0,
        Cooldown: 1.5,
        Lifespan: 240,
        Limit: 7,
        Range: 19,
        ChargeTime: 0, 
        ExplosionRange: 4.5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    ['Grenadier3 (PVP)']: {
        Unlocks: 6,
        Health: 300,
        Speed: 2.5,
        Defense: 1,
        Damage: 80,
        SpawnTime: 40,
        Heal: 0,
        Cooldown: 1.25,
        Lifespan: 240,
        Limit: 7,
        Range: 20,
        ChargeTime: 0, 
        ExplosionRange: 4.5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    ['RiotGuard1 (PVP)']: {
        Unlocks: 4,
        Health: 1000,
        Speed: 2.5,
        MaxSpeed: 7,
        Defense: 1,
        Damage: 50,
        SpawnTime: 50,
        MaxHits: 10,
        Cooldown: 1.5,
        Lifespan: 240,
        Limit: 4,
        Range: 4,
        ChargeTime: 4, 
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    ['RiotGuard2 (PVP)']: {
        Unlocks: 6,
        Health: 2600,
        Speed: 2.5,
        MaxSpeed: 7,
        Defense: 15,
        Damage: 50,
        SpawnTime: 50,
        MaxHits: 10,
        Cooldown: 1,
        Lifespan: 240,
        Limit: 4,
        Range: 4,
        ChargeTime: 3, 
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    ['FieldMedic1 (PVP)']: {
        Unlocks: 5,
        Health: 300,
        Speed: 2.5,
        Defense: 0,
        SpawnTime: 35,
        Heal: 15,
        MaxHits: 6,
        Cooldown: 0.2,
        Lifespan: 240,
        Limit: 3,
        Range: 35,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    ['FieldMedic2 (PVP)']: {
        Unlocks: 6,
        Health: 600,
        Speed: 2.5,
        Defense: 0,
        SpawnTime: 30,
        Heal: 20,
        MaxHits: 8,
        Cooldown: 0.2,
        Lifespan: 240,
        Limit: 3,
        Range: 35,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    IceTurret1: {
        Range: 10,
        Damage: 10,
        Cooldown: 0.45,
        FreezeTime: 2,
        DebuffLength: 5,
        SlowPercent: 25,
        MaxSlow: 50,
        Lifespan: 45,
        Health: 1000,
    },
    IceTurret2: {
        Range: 12.5,
        Damage: 20,
        Cooldown: 0.35,
        FreezeTime: 2,
        DebuffLength: 5,
        SlowPercent: 25,
        MaxSlow: 50,
        Lifespan: 45,
        Health: 1000,
    },
    IceTurret3: {
        Range: 15,
        Damage: 30,
        Cooldown: 0.3,
        FreezeTime: 2,
        DebuffLength: 5,
        SlowPercent: 30,
        MaxSlow: 60,
        Lifespan: 45,
        Health: 1000,
    },
    Sentry: {
        Range: 18,
        Health: 20,
        Cooldown: 0.6,
        Damage: 1,
        ExplosionDamage: 0,
        TimeBetweenMissiles: 0,
        MissileAmount: 0,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
        Attributes: {
            SendTime: 1.25,
            ScrapCost: 8,
            Lifespan: 30,
        },
    },
    RifleSentry: {
        Range: 20,
        Health: 40,
        Cooldown: 0.25,
        Damage: 2,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
        Attributes: {
            SendTime: 1.5,
            ScrapCost: 45,
            Lifespan: 30,
        },
    },
    MinigunSentry: {
        Range: 20,
        Health: 60,
        Cooldown: 0.1,
        Damage: 3,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {
            SendTime: 1.75,
            ScrapCost: 180,
            Lifespan: 45,
        },
    },
    WarMachineSentry: {
        ExplosionDamage: 70,
        TimeBetweenMissiles: 4,
        MissileAmount: 2,
        Range: 24,
        Health: 300,
        Cooldown: 0.1,
        Damage: 3,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {
            SendTime: 1.75,
            ScrapCost: 340,
            Lifespan: 60,
        },
    },
    ['Sentry (PVP)']: {
        Range: 18,
        Health: 20,
        Cooldown: 0.45,
        Damage: 2,
        ExplosionDamage: 0,
        TimeBetweenMissiles: 0,
        MissileAmount: 0,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
        Attributes: {
            SendTime: 1.25,
            ScrapCost: 16,
            Lifespan: 30,
        },
    },
    ['RifleSentry (PVP)']: {
        Range: 20,
        Health: 40,
        Cooldown: 0.2,
        Damage: 2,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
        Attributes: {
            SendTime: 1.5,
            ScrapCost: 32,
            Lifespan: 30,
        },
    },
    ['MinigunSentry (PVP)']: {
        Range: 20,
        Health: 60,
        Cooldown: 0.15,
        Damage: 6,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {
            SendTime: 1.75,
            ScrapCost: 120,
            Lifespan: 45,
        },
    },
    ['WarMachineSentry (PVP)']: {
        ExplosionDamage: 60,
        TimeBetweenMissiles: 4,
        MissileAmount: 2,
        Range: 24,
        Health: 250,
        Cooldown: 0.1,
        Damage: 10,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Attributes: {
            SendTime: 1.75,
            ScrapCost: 250,
            Lifespan: 60,
        },
    },
    Humvee: {
        Health: 50,
        Damage: 0,
        ExplosionDamage: 0,
        TimeBetweenMissiles: 0,
        Cooldown: 0.2,
        Range: 5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    ['Humvee 2']: {
        Health: 80,
        Damage: 0,
        Cooldown: 0.2,
        Range: 5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    ['Humvee 3']: {
        Health: 100,
        Damage: 3,
        Cooldown: 0.2,
        Range: 30,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Tank: {
        Health: 500,
        Damage: 8,
        Cooldown: 0.2,
        Range: 30,
        ExplosionDamage: 40,
        TimeBetweenMissiles: 2,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    ['Railgun Tank']: {
        Health: 1600,
        Damage: 22,
        Cooldown: 0.15,
        Range: 30,
        ExplosionDamage: 100,
        TimeBetweenMissiles: 3,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    ['Humvee (PVP)']: {
        Health: 60,
        Damage: 0,
        ExplosionDamage: 0,
        TimeBetweenMissiles: 0,
        Cooldown: 0.2,
        Range: 5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    ['Humvee 2 (PVP)']: {
        Health: 100,
        Damage: 0,
        Cooldown: 0.2,
        Range: 5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    ['Humvee 3 (PVP)']: {
        Health: 100,
        Damage: 3,
        Cooldown: 0.2,
        Range: 30,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    ['Tank (PVP)']: {
        Health: 500,
        Damage: 8,
        Cooldown: 0.2,
        Range: 30,
        ExplosionDamage: 40,
        TimeBetweenMissiles: 2,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    ['Railgun Tank (PVP)']: {
        Health: 1600,
        Damage: 22,
        Cooldown: 0.15,
        Range: 30,
        ExplosionDamage: 100,
        TimeBetweenMissiles: 3,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Mark1: {
        Health: 400,
        Damage: 8,
        Cooldown: 0.2,
        Range: 30,
        SpawnTime: 60,
        ExplosionDamage: 0,
        TimeBetweenMissiles: 0,
        MissileAmount: 0,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Mark1Rocket: {
        Health: 400,
        Damage: 8,
        Cooldown: 0.2,
        Range: 30,
        SpawnTime: 40,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 5,
        MissileAmount: 1,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Mark2: {
        Health: 750,
        Damage: 12,
        Cooldown: 0.15,
        Range: 25,
        SpawnTime: 40,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 5,
        MissileAmount: 1,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Mark3: {
        Health: 1200,
        Damage: 10,
        Cooldown: 0.08,
        Range: 25,
        SpawnTime: 40,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 3,
        MissileAmount: 1,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Mark4: {
        Health: 2000,
        Damage: 10,
        Cooldown: 0.05,
        Range: 100,
        SpawnTime: 40,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 3,
        MissileAmount: 4,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Mark5: {
        Health: 5000,
        Damage: 20,
        Cooldown: 0.05,
        Range: 100,
        SpawnTime: 40,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 3,
        MissileAmount: 4,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    //biologist
    Sunflower0: {
        Health: 50,
        Damage: 6,
        Cooldown: 1.1,
        PoisonDamage: 0,
        PoisonTick: 0,
        ExplosionRange: 0,
        PoisonTime: 0,
        Slowdown: 0,
        ProjectileSpeed: 0,
        ConfusionTime: 0,
        ConfusionCooldown: 0,
        Lifespan: 20,
        Range: 15,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    Sunflower1: {
        Health: 100,
        Damage: 10,
        Cooldown: 1.1,
        Lifespan: 20,
        Range: 15,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
    },
    Sunflower2: {
        Health: 200,
        Damage: 12,
        Cooldown: 1.1,
        Lifespan: 20,
        Range: 17,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Sunflower3: {
        Health: 400,
        Damage: 28,
        Cooldown: 1,
        Lifespan: 20,
        Range: 19.5,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Sunflower4: {
        Health: 800,
        Damage: 55,
        Cooldown: 0.8,
        Lifespan: 20,
        Range: 22.5,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
    },
    Ivy1: {
        Health: 100,
        Damage: 8,
        PoisonDamage: 1,
        Cooldown: 2,
        PoisonTick: 0.75,
        Lifespan: 20,
        Range: 14,
        ExplosionRange: 3,
        PoisonTime: 4.5,
        Slowdown: 5,
        ProjectileSpeed: 20,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    Ivy2: {
        Health: 200,
        Damage: 12,
        PoisonDamage: 2,
        Cooldown: 1.8,
        PoisonTick: 0.75,
        Lifespan: 20,
        Range: 15.5,
        ExplosionRange: 4,
        PoisonTime: 4.5,
        Slowdown: 7.5,
        ProjectileSpeed: 20,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    Ivy3: {
        Health: 400,
        Damage: 25,
        PoisonDamage: 4,
        Cooldown: 1.8,
        PoisonTick: 0.6,
        Lifespan: 20,
        Range: 17,
        ExplosionRange: 4.5,
        PoisonTime: 4.5,
        Slowdown: 7.5,
        ProjectileSpeed: 20,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    Ivy4: {
        Health: 800,
        Damage: 45,
        PoisonDamage: 5,
        Cooldown: 1.5,
        PoisonTick: 0.65,
        Lifespan: 20,
        Range: 18.5,
        ExplosionRange: 4.5,
        PoisonTime: 5.2,
        Slowdown: 12.5,
        ProjectileSpeed: 20,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
    },
    Nightshade3: {
        Health: 400,
        Damage: 50,
        Cooldown: 3,
        Lifespan: 20,
        Range: 30,
        ConfusionTime: 1,
        ConfusionCooldown: 4,
        Detections: {
            Hidden: false,
            Flying: true,
            Lead: false,
        },
    },
    Nightshade4: {
        Health: 800,
        Damage: 135,
        Cooldown: 2.75,
        Lifespan: 20,
        Range: 35,
        ConfusionTime: 1.25,
        ConfusionCooldown: 4,
        Detections: {
            Hidden: false,
            Flying: true,
            Lead: false,
        },
    },
    //commander
    GunnerAPC: {
        Health: 250,
        Damage: 10,
        Burst: 0,
        Cooldown: 0.2,
        Range: 30,
        ExplosionRange: 0,
        SpawnCount: 2,
    },
    MissileAPC: {
        Health: 400,
        Damage: 50,
        Burst: 4,
        Cooldown: 2,
        Range: 25,
        ExplosionRange: 5,
        SpawnCount: 1,
    },
    //poop camp
    Elf: {
        Health: 16,
        Damage: 0,
        Cooldown: 0,
        BurstCooldown: 0,
        BurstCount: 1,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        SpawnTime: 15,
        SpawnCount: 1,
        ExplosionRange: 0,
        Range: 1.5,
        Limit: 10,
    },
    SnowballElf: {
        Health: 20,
        Damage: 5,
        Cooldown: 2.5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
        SpawnTime: 20,
        SpawnCount: 1,
        Range: 18,
        Limit: 4,
    },
    BomberElf: {
        Health: 22,
        Damage: 60,
        Cooldown: 0,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: true,
        },
        SpawnTime: 25,
        ExplosionRange: 8,
        SpawnCount: 1,
        Range: 2.5,
        Limit: 10,
    },
    GuardianElf: {
        Health: 75,
        Defense: 30,
        Damage: 28,
        Cooldown: 0.5,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        SpawnTime: 20,
        SpawnCount: 1,
        Range: 7.5,
        Limit: 4,
    },
    UpgradedGuardianElf: {
        Health: 10,
        Defense: 50,
        Damage: 42,
        Cooldown: 0.5,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        SpawnTime: 20,
        SpawnCount: 1,
        Range: 7.5,
        Limit: 4,
    },
    CannoneerElf: {
        Health: 30,
        Damage: 5,
        Cooldown: 0.5,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: false,
        },
        SpawnTime: 25,
        SpawnCount: 1,
        Range: 22,
        Limit: 4,
    },
    RippedElf: {
        Health: 800,
        Damage: 360,
        SpawnTime: 80,
        Detections: {
            Hidden: false,
            Flying: false,
            Lead: true,
        },
        Cooldown: 6.7,
        Range: 40,
        ExplosionRange: 12,
        Limit: 1,
    },
    GunnerElf: {
        Health: 40,
        Damage: 5,
        SpawnTime: 30,
        Detections: {
            Hidden: true,
            Flying: false,
            Lead: false,
        },
        Cooldown: 0.2,
        BurstCooldown: 1,
        BurstCount: 6,
        SpawnCount: 1,
        Range: 22,
        Limit: 4,
    },
    UpgradedGunnerElf: {
        Health: 50,
        Damage: 7,
        SpawnTime: 30,
        Detections: {
            Hidden: true,
            Flying: true,
            Lead: false,
        },
        Cooldown: 0.2,
        BurstCooldown: 1,
        BurstCount: 6,
        SpawnCount: 2,
        Range: 25,
        Limit: 4,
    },
    ['Flame - Level 3']: {
        BurnDamage: 1,
        BurnTick: 0.5,
        BurnTime: 2,
        MaxHits: 3,
        StunLength: 0,
        ExplosionDamage: 0,
        ExplosionRange: 0,
    },
    ['Flame - Level 4']: {
        BurnDamage: 3,
        BurnTick: 0.5,
        BurnTime: 3,
        MaxHits: 4,
        StunLength: 0,
        ExplosionDamage: 0,
        ExplosionRange: 0,
    },
    ['Flame - Level 5']: {
        BurnDamage: 6,
        BurnTick: 0.5,
        BurnTime: 4,
        MaxHits: 6,
        StunLength: 0,
        ExplosionDamage: 0,
        ExplosionRange: 0,
    },
    ['Shock - Level 4']: {
        BurnDamage: 0,
        BurnTick: 0,
        BurnTime: 0,
        MaxHits: 3,
        StunLength: 0.3,
        ExplosionDamage: 0,
        ExplosionRange: 0,
    },
    ['Shock - Level 5']: {
        BurnDamage: 0,
        BurnTick: 0,
        BurnTime: 0,
        MaxHits: 4,
        StunLength: 0.45,
        ExplosionDamage: 0,
        ExplosionRange: 0,
    },
    ['Explosive - Level 5']: {
        BurnDamage: 0,
        BurnTick: 0,
        BurnTime: 0,
        MaxHits: 0,
        StunLength: 0,
        ExplosionDamage: 35,
        ExplosionRange: 5,
    },
};
